### ISSUE TITLE
Mixin does not support static interface method injections

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/Mixin#11]
See SpongePowered/Mixin#318

**Comment by asiekierka** [comment]
https://github.com/FabricMC/Mixin/commit/804bd2c0225f71d38816e190eb88cbea1f769abd

**Comment by Pyrofab** [comment]
Actually this is not fixed, there is still a check preventing public methods in mixin. Because interface static methods can only be public, they blow up.

**Comment by Chocohead** [comment]
The accessibility of a mixin doesn't have to match the target method though? So it at least possible to most extents now

**Comment by Pyrofab** [comment]
The thing is, Mixin requires an interface mixin to be an interface itself. And interfaces cannot have private methods.

**Comment by InsomniaKitten** [comment]
The bug isn't that there is a check preventing public methods in that case, the bug would be that it does not allow class mixins for interface injections? There shouldn't be a type requirement there.

**Comment by asiekierka** [comment]
>The bug isn't that there is a check preventing public methods in that case, the bug would be that it does not allow class mixins for interface injections? There shouldn't be a type requirement there.

For interface injections, use an interface and static/default methods. That should work fine, at least - I tested it that way.

**Comment by asiekierka** [comment]
Wait... I know what I did wrong.

**Comment by asiekierka** [comment]
I made Loader *build* with new Mixin but not *require* new Mixin on the launcher side. Use 0.4.6.

**Comment by Siphalor** [comment]
Seems like it doesn't work like it should.
Code: https://pastebin.com/C6ThZSCk
Log: https://pastebin.com/bKNPnhyZ

btw there are only notes but no errors in the log.

**Comment by Prospector** [comment]
Definitely doesn't seem to be working currently; not sure if a recent break or not though.

**Comment by Siphalor** [comment]
It never worked iirc
