### ISSUE TITLE
Mixin 0.8.6 has been released on origin repository

### ISSUE THREAD

**Issue by Kichura** [FabricMC/Mixin#140]
The commit list can be found [here](https://github.com/SpongePowered/Mixin/compare/releases%2F0.8.5...releases%2F0.8.6), Are there plans on updating this repository to make use of these changes too?

**Comment by LlamaLad7** [comment]
Most of the changes were just to catch up with our fork. There are nonetheless one or two bug fixes which i am planning to pull in soon.

**Comment by Kichura** [comment]
Closing this as mixin 0.8.6 is now on this repo.
