### ISSUE TITLE
Annotation processor rejects interface injections

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/Mixin#15]
Attempting to build a mod using an injection in an interface static method errors, displaying `error: Injector in interface is unsupported`.
[This check](https://github.com/FabricMC/Mixin/blob/master/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixinElementHandlerInjector.java#L150-L152) should probably be removed now that #13 has been merged.

**Comment by coderbot16** [comment]
This issue appears to have resurfaced with the move to Mixin 0.8, including injecting into `default` methods. Can it be reopened? Or perhaps another issue could be opened.
