### ISSUE TITLE
Incompability with ASM5 

### ISSUE THREAD

**Issue by rafi67000** [FabricMC/Mixin#153]
Type.NULL_TYPE didn't exist in ASM5 which results in incomability with older mc versions that ships ASM5
https://github.com/FabricMC/Mixin/blob/81284c8401b657f5805b670f4628a734b4561807/src/main/java/org/spongepowered/asm/util/asm/MixinVerifier.java#L64

**Comment by modmuss50** [comment]
Can you not update ASM? I know for sure that the latest ASM version works fine on really old betas (as I tried it the other day).

**Comment by modmuss50** [comment]
Nothing wrong with that, neo forge uses this version of mixin in modern versions.

My main worry with is its going to get harder and harder to keep support for old asm versions, and its not something we can easily test. `NULL_TYPE` was added to ASM 6 years ago, and the latest asm version should be a drop in upgrade.

**Comment by modmuss50** [comment]
Been thinking about this some more, one thing you could possibly do is bundle and repackage mixin + asm in your mod, this way you can make use of the latets mixin and asm without interferring with other mods and the existing asm version.

**Comment by modmuss50** [comment]
Yeah, I think that's going to be the best solution here. Thanks and have fun 👍
