### ISSUE TITLE
dont know if this is a fabric api issue or a mixin issue.

### ISSUE THREAD

**Issue by MrPurple6411** [FabricMC/Mixin#22]
[crash-2019-06-14_05.25.51-client.txt](https://github.com/FabricMC/Mixin/files/3290430/crash-2019-06-14_05.25.51-client.txt)

# Fabric Properties
minecraft_version=1.14.3-pre2
yarn_mappings=1.14.3-pre2+build.10
loader_version=0.4.8+build.155

#Fabric api
fabric_version=0.3.0+build.184           <---- 181 works fine but 183 and 184 give this crash.

**Comment by modmuss50** [comment]
that version of fabric api is not compatible with 1.14.3. not a mixin issue.

**Comment by MrPurple6411** [comment]
odd why would 181 work but 183 and 184 fail

**Comment by MrPurple6411** [comment]
but thanx
