### ISSUE TITLE
Interfaces cannot be injected into anymore

### ISSUE THREAD

**Issue by haykam821** [FabricMC/Mixin#34]
This was supposedly fixed with #13, but somehow the fix is no longer present.

**Comment by modmuss50** [comment]
An example would be very helpful. Seems odd that upstream mixin doesnt have this by now? or is it broken from upstream? that will need testing.

**Comment by haykam821** [comment]
Here is an example:
```java
@Mixin(DynamicRegistryManager.class)
public interface DynamicRegistryManagerMixin {
	@Inject(method = "method_30531", at = @At(value = "INVOKE", target = "Lnet/minecraft/util/registry/DynamicRegistryManager;register(Lcom/google/common/collect/ImmutableMap$Builder;Lnet/minecraft/util/registry/RegistryKey;Lcom/mojang/serialization/MapCodec;Z)Lcom/google/common/collect/ImmutableMap$Builder;", ordinal = 0), locals = LocalCapture.CAPTURE_FAILHARD)
	public static void registerThingDynamicRegistry(ImmutableMap.Builder<RegistryKey<? extends Registry<?>>, DynamicRegistryManager.Info<?>> builder) {
		DynamicRegistryManager.register(builder, Main.THING_KEY, Thing.CODEC, true);
	}
}
```

**Comment by modmuss50** [comment]
I cherry picked that PR over, that was quite easy to do.

However java isnt happy with the added method spitting out this lovely error:

`java.lang.IncompatibleClassChangeError: Method 'void net.minecraft.util.registry.DynamicRegistryManager.handler$zdg000$registerThingDynamicRegistry(org.spongepowered.asm.mixin.injection.callback.CallbackInfo)' must be InterfaceMethodref constant`

Im not sure how this was handled before, any ideas would be a great help.

I havent tested it, but default methods may work.

**Comment by coderbot16** [comment]
https://github.com/SpongePowered/Mixin/issues/421 would suggest that injecting into default methods at the very least is supported by upstream Mixin. I'd assume that upstream Mixin supports injections into `public static` methods as well. That would mean that something is likely broken from upstream.

**Comment by sfPlayer1** [comment]
I think the exception means that mixin injected a normal method reference instead of an interface method reference to call a method owned by an interface. In ASM this would be a lack of setting `itf=true` in the related `invokestatic`.

For the above example this means that `invokestatic handler$zdg000$registerThingDynamicRegistry` was emitted with `itf=false` in its last arg.

**Comment by OverlordsIII** [comment]
![image](https://user-images.githubusercontent.com/69648849/99131099-1bcbe900-25c7-11eb-8d2f-815cdad26bea.png)
doesn't look like upstream mixin supports it either currently

**Comment by squeek502** [comment]
Relevant Mixin issue is https://github.com/SpongePowered/Mixin/issues/318
