### ISSUE TITLE
Expected local variable type is null

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/Mixin#4]
One of the expected local variable types ends up being `Lnull;` when using this Inject in a `LootManager` mixin:  
`@Inject(method = "onResourceReload", at = @At(value = "INVOKE", target = "Ljava/util/Map;put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"), locals = LocalCapture.PRINT)`

[Output of `LocalCapture.PRINT`](https://gist.github.com/Juuxel/fc0989726fb831135a938ec1ccdc2f05)

**Comment by liach** [comment]
Might need to use `@Coerce` for your case unfortunately

**Comment by Juuxel** [comment]
Can't reproduce since Loom is having some problems with the older versions of Minecraft that still had this variant of `LootManager.onResourceReload/apply`.
