### ISSUE TITLE
@Redirect(..., at = @At("HEAD")) targets wrong instruction

### ISSUE THREAD

**Issue by ewewukek** [FabricMC/Mixin#48]
i've been trying to hook into `HeldItemRenderer.renderFirstPersonItem`.
`@Redirect` targets method's first instruction (`LabelNode`) which seems ok, but fails in `RedirectInjector.inject`

minimal project reproducing this bug(?): https://github.com/ewewukek/fabric-mixin-test

**Comment by TheGlitch76** [comment]
You can't redirect a Label...
You're probably looking for `@Inject`

**Comment by ewewukek** [comment]
you're totally right. i was redirecting a call to this method inside `renderItem` but didn't change the annotation when switched to injecting directly into `renderFirstPersonItem`.

thank's for reply and sorry for useless issue)
