### ISSUE TITLE
Gradle's Time Tracker using AP source version causing warning when running with Java 16

### ISSUE THREAD

**Issue by NinjaPhenix** [FabricMC/Mixin#61]
https://github.com/FabricMC/Mixin/blob/75e3e39a83aa76377104a9cac6592db4c68f4d68/src/ap/java/org/spongepowered/tools/obfuscation/MixinObfuscationProcessor.java#L82-L87
*Should* be safe to just return `SourceVersion.latestSupported()` if it is greater than `RELEASE_8`.

Fixed by: https://github.com/FabricMC/Mixin/pull/53/.

**Comment by modmuss50** [comment]
This was fixed, included with loader 0.12
