### ISSUE TITLE
Cannot invoke a method that contains private inner class in its parameter list

### ISSUE THREAD

**Issue by aleck099** [FabricMC/Mixin#81]
How do you call `net.minecraft.server.command.TeleportCommand.teleport()`?
`@Invoke` it?
This is its parameter list:
`teleport(ServerCommandSource source, Entity target, ServerWorld world, double x, double y, double z, Set<PlayerPositionLookS2CPacket.Flag> movementFlags, float yaw, float pitch, @Nullable LookTarget facingLocation)`
You may have found the problem: `LookTarget` is a private inner class of `TeleportCommand`.
So how can we make a private inner class `public`?

**Comment by Technici4n** [comment]
One way is to use an access widener. Another is to use `@Coerce Object` instead of the inner class IIRC.
